### ISSUE TITLE
Game renders in small boxes at the bottom of the window

### ISSUE THREAD

**Issue by jrbudda** [jrbudda/Vivecraft_113#1]
If your game looks like this:

![image](https://user-images.githubusercontent.com/1927235/53273848-2d6ab000-36c3-11e9-97e8-edcd2c05084c.png)

Turn off fullscreen with F11 and tell us if you can reliably reproduce this issue.

**Comment by ImNotShady** [comment]
I do get this similar issue and could not find anyone else having this issue on my server I run.
I do not launch the game in fullscreen and it still occurs but hitting F11 to enable fullscreen fixes the issue strangely enough. Seems like anything that forces a re-render or changes to anything involving resolution fixes the issue including changing render scale slider and as changing view distance for example.

After I do have everything rendering properly but the issue manifests again whenever any entity with the glowing effect, the effect you get from spectral arrows, is in view which then causes everything UI related to smash into the left bottom corner of my view. While the world continues to render fine. This issue is not seen in the desktop window though.

I do get spammed with OpenGL 1282 errors in game chat which I just disabled the printing for since it doesn't seem to cause any immediate issue until I started getting this strange box in corner bug, im not sure if its related at all. 
But these issues did not start happening until I started to mess with render scale factoring, but still persists even when I reset it back to 1.0 so I am not sure if its related but it is notable.
I know its not much but here is the log and a screenshot.
[latest.log](https://github.com/jrbudda/Vivecraft_113/files/2946194/latest.log)
![20190308085326_1](https://user-images.githubusercontent.com/47245976/54034984-45900400-4186-11e9-80f2-36f2c7120b25.jpg)

**Comment by jrbudda** [comment]
Could you see if you get the same thing with the current revision of Vivecraft 1.13? If so i'd be interesting in your option txt files from /.minecraft

**Comment by ImNotShady** [comment]
Sorry for the delay, I was fiddling with the settings exhaustively to try to get the issue to start again after I installed the latest revision. I did a full wipe of the instance so everything could start fresh. But to all of my attempts I could not recreate the issue with this revision. Although I am still getting the same OpenGL errors but that is unrelated it seems. So I am going to assume this issue to be resolved in the latest revision.
Thanks for looking into it and fixing the issue :)
